import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";
import SideNavbar from "./sideNavbar/SideNavbar";
import Login from "./login/page";
import UpperNavBar from "./UpperSideBar/page";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Article",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isLogin = false;

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${cn("", inter.className, {
          "debug-screens": process.env.NODE_ENV === "development",
        })} `}
      >
        <div className="grid grid-cols-[0.5fr_5fr] grid-rows-[1fr] gap-x-[0px] gap-y-[0px] overflow-hidden">
          {isLogin ? (
            <Login />
          ) : (
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
            >
              <div className="">
                <SideNavbar />
              </div>

              <div className="grid  grid-rows-[0.01fr_fr] gap-x-[0px] gap-y-[0px] w-full ">
                <UpperNavBar />
                <div className="mt-14 w-full p-8 ">{children}</div>
              </div>
            </ThemeProvider>
          )}
        </div>
      </body>
    </html>
  );
}
